##################################################  devops-gateway  ###########################
devops_gateway_image: private-registry.rootcloud.com/operations/devops-gateway:master_7a314bf9_20200923-140330


####################################################  devops-web  ##############################
devops_web_image: private-registry.rootcloud.com/cicd/devops-web:master_7b5e668_20200930-090114


####################################################  devops-mds  ##############################
devops_mds_image: private-registry.rootcloud.com/cicd/devops-mds:master_de4313d_20201019-200046


####################################################  devops-eureka  ##############################
devops_eureka_image: private-registry.rootcloud.com/operations/devops-eureka:master_a9b343a_20200909-180844


####################################################  devops-system  ##############################
devops_system_image: private-registry.rootcloud.com/cicd/devops-system:master_c84e900_20201015-085033


####################################################  common  ##############################
mds_app_namespace: mds
image_pull_secret: regsecret
mds_app_state: present
tolerate_key: mds
nodeselector_key: zone
nodeselector_value: mds
HELPDESKMYSQLHOST: 
HELPDESKMYSQLPORT:
HELPDESKMYSQLPWD:
MYSQLHOST:
MYSQLPORT:
MYSQLPWD:
REDISHOST:
REDISPORT:
REDISPWD:


